---
title: 'International Trade: Assignment 2'
runningheader: 'Assignment 2'
author: |
  Carlos Lezama, Marco Hinojosa, \
  Luis Jiménez and Antonio Carbonell
date: 'November 30, 2021'
output:
  tufte::tufte_handout:
    citation_package: natbib
bibliography: skeleton.bib
link-citations: yes
---

```{r setup, include=FALSE}
library(tufte)
library(tidyverse)

knitr::opts_chunk$set(
  cache.extra = packageVersion('tufte'),
  cache = TRUE,
  echo = FALSE,
  fig.fullwidth = TRUE,
  fig.height = 6,
  fig.pos = '!h',
  fig.width = 12,
  message = FALSE,
  out.extra = '',
  out.width = '100%',
  warning = FALSE
)

options(htmltools.dir.version = FALSE)
```

# Theoretical section

\newpage

# Data section

```{r}
source('src.R')

ggplot() +
  geom_line(aes(
    x = gl.ALL3$year,
    y = gl.ALL3$index,
    colour = 'Three-digit SITC'
  )) +
  geom_line(aes(
    x = gl.ALL5$year,
    y = gl.ALL5$index,
    colour = 'Five-digit SITC'
  )) +
  theme_minimal() +
  labs(title = 'Grubel and Lloyd Index Weighted Average',
       x = 'year',
       y = NULL) +
  scale_colour_manual(name = '', values = colours) +
  scale_x_continuous(breaks = seq(1990, 2010, 2))
```
